/**
 * RD & Company CRM - Task Management Data
 */

export const taskTableData = {
  columns: [
    { Header: "Title", accessor: "title", width: "25%" },
    { Header: "Description", accessor: "description", width: "30%" },
    { Header: "Assigned To", accessor: "assigned_to", width: "15%" },
    { Header: "Priority", accessor: "priority", width: "10%" },
    { Header: "Status", accessor: "status", width: "10%" },
    { Header: "Due Date", accessor: "due_date", width: "10%" },
  ],

  rows: [
    {
      id: 1,
      title: "Follow up with Client ABC",
      description: "Call client to discuss pending order and provide updates on delivery timeline",
      assigned_to: "John Sales",
      assigned_to_id: 1,
      priority: "high",
      status: "pending",
      due_date: "2024-01-20",
      created_date: "2024-01-15",
      created_by: 1,
    },
    {
      id: 2,
      title: "Prepare monthly report",
      description: "Compile sales data and create comprehensive monthly performance report",
      assigned_to: "Sarah Office",
      assigned_to_id: 2,
      priority: "medium",
      status: "done",
      due_date: "2024-01-18",
      created_date: "2024-01-10",
      created_by: 1,
    },
    {
      id: 3,
      title: "Update product catalog",
      description: "Review and update product information in the system with latest pricing",
      assigned_to: "Mike Sales",
      assigned_to_id: 3,
      priority: "low",
      status: "completed",
      due_date: "2024-01-15",
      created_date: "2024-01-08",
      created_by: 1,
    },
    {
      id: 4,
      title: "Process pending orders",
      description: "Review and process all pending orders from the last week",
      assigned_to: "Sarah Office",
      assigned_to_id: 2,
      priority: "urgent",
      status: "pending",
      due_date: "2024-01-16",
      created_date: "2024-01-14",
      created_by: 1,
    },
    {
      id: 5,
      title: "Client meeting preparation",
      description: "Prepare presentation and materials for upcoming client meeting",
      assigned_to: "John Sales",
      assigned_to_id: 1,
      priority: "high",
      status: "done",
      due_date: "2024-01-17",
      created_date: "2024-01-12",
      created_by: 1,
    },
    {
      id: 6,
      title: "Inventory check",
      description: "Conduct weekly inventory check and update stock levels",
      assigned_to: "Sarah Office",
      assigned_to_id: 2,
      priority: "medium",
      status: "pending",
      due_date: "2024-01-19",
      created_date: "2024-01-13",
      created_by: 1,
    },
  ],
};
